### ISSUE TITLE
Clarification Needed As To Running Beta Build

### ISSUE THREAD

**Issue by GamerBoi9873** [Roblox/avatar-evolution#10]
The instructions say "This is a custom build of ROBLOX Studio. Make sure to copy the folder from this .zip to your computer before running the build — don’t run directly from .zip.". What does that mean? There's multiple folders in the .zip file.

**Comment by jovannic** [comment]
Just means that you need to extract all the files to a folder before you run it.

On Windows if you just browsed into the zip and double clicked the exe without extracting that it wouldn't work.

**Comment by GamerBoi9873** [comment]
Do you answer from emails?
