### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by cameratvcon** [Roblox/avatar-evolution#12]
when i press login i get a popup saying theres a script error on this page
once that goes it says error displaying captcha

**Comment by jbrosnihan-roblox** [comment]
What happens if you launch regular Studio by editing a place from the website, then close regular studio and open AvatarEvolution Studio? Are you logged in then?

**Comment by jbrosnihan-roblox** [comment]
Is this resolved for you?

**Comment by jbrosnihan-roblox** [comment]
Closing for now. Let me know if you're still having issues.
