### ISSUE TITLE
(Question/Suggestion) Property for Height maps + Scaling

### ISSUE THREAD

**Issue by dev-sda1** [Roblox/avatar-evolution#13]
Will we be seeing the implementation of height maps in the near future as well?
Also it'd be awesome if we were able to adjust the scale of all the textures instead of just metal and roughness.

What it looks like on Roblox (without height maps)
![image](https://user-images.githubusercontent.com/43112896/70864957-b6532080-1f4f-11ea-8da7-1cda4a20a974.png)

What it would look like (with height maps)
https://www.textures.com/download/3dscans0547/136346?q=cobble#gallery-3

**Comment by MicahHinckley** [comment]
I would absolutely love this feature.

**Comment by sluncelyna2** [comment]
Epic amazing your are is been has know feature.

**Comment by Rocky28447** [comment]
I believe you are referring to displacement maps, not heightmaps.

**Comment by jbrosnihan-roblox** [comment]
This is an open question internally. It seems likely we'll add this eventually, but there is no timeline.
