### ISSUE TITLE
I have NO CLUE how to actually install this.

### ISSUE THREAD

**Issue by Quvintu** [Roblox/avatar-evolution#15]
I'm finding the instructions 'copy _the folder_ from the .zip file to your computer' very unclear. Can somebody please explain **exactly** how to install and run the software? Thanks in advance!

**Comment by Biddn** [comment]
![CoordinatedNeedyCommongonolek-size_restricted](https://user-images.githubusercontent.com/26294370/70937009-35585f80-2009-11ea-8b7f-306d15cc4a4a.gif)

1. Download the file (According to the OS you're using)
2. Open it with a .zip extractor 
3. Select all files inside the .zip
4. Drop it into a folder onto your desktop

**Comment by jovannic** [comment]
I added some quick instructions for both platforms to the site. Let me know if that resolves this for you.

If that's not clear enough please let me know and I'll add more explicit details like above.

**Comment by jovannic** [comment]
Closing for now. Re-open if instructions on the site are unclear.
