### ISSUE TITLE
Link to example rbxl file redirects to website

### ISSUE THREAD

**Issue by Reshiram110** [Roblox/avatar-evolution#2]
Currently, the link to download the rbxl file for the new character controller system is broken, it redirects back to the website.

Problematic line : https://github.com/Roblox/avatar-evolution/blame/gh-pages/index.md#L48

**Comment by tomgie** [comment]
I'm sure the reasoning is because it hasn't been released yet.

**Comment by jovannic** [comment]
Yeah known issue... Placeholder link. Hopefully we'll get the place file posted today.

**Comment by RocketFighter** [comment]
The link for "Read about how to import skinned meshes here" also has the same issue.

**Comment by jovannic** [comment]
Yep we're working on that too :)

**Comment by jovannic** [comment]
RBXL and character controller docs are up now

**Comment by jovannic** [comment]
All fixed
