### ISSUE TITLE
Metalness/Metalness scale + Reflections not working.

### ISSUE THREAD

**Issue by LaAerooo** [Roblox/avatar-evolution#3]
I'm on a windows pc, and sliding the metalness does nothing, as well as adding a Metalness map.

Reflections also don't show up when sliding the roughness scale, but the sun does reflect and it changes as expected.

VIDEO (ignore the ending, I was on another tab lol)
https://gfycat.com/jadedpersonalgoa

**Comment by tomgie** [comment]
From what I am aware of, Roblox doesn't reflect objects, if that's what you where getting at.

**Comment by jbrosnihan-roblox** [comment]
Metalness doesn't have an apparent effect unless you set up your place to use physically based lighting. To do this, set:

Lighting.EnvironmentDiffuseScale = 1
Lighting.EnvironmentSepcularScale = 1
Lighting.OutdoorAmbient = 0,0,0
Lighting.Ambient = 0,0,0

Currently EnvironmentDiffuseScale and EnvironmentSpecularScale are hidden in the properties window. You can still modify them from Lua. We'll fix that in the next release and add an explanation to our documentation.

**Comment by Rocky28447** [comment]
"``Lighting.EnvironmentSepcularScale = 1``"

I believe this should be ``Lighting.EnvironmentSpecularScale = 1``.

**Comment by Rocky28447** [comment]
Anyway, this would definitely explain why others and I have not seen the effects of PBR take hold in production studio even though the flag has been enabled.

**Comment by LaAerooo** [comment]
> Metalness doesn't have an apparent effect unless you set up your place to use physically based lighting. To do this, set:
> 
> Lighting.EnvironmentDiffuseScale = 1
> Lighting.EnvironmentSpecularScale = 1 **--(Fixed my typo)**
> Lighting.OutdoorAmbient = 0,0,0
> Lighting.Ambient = 0,0,0
> 
> Currently EnvironmentDiffuseScale and EnvironmentSpecularScale are hidden in the properties window. You can still modify them from Lua. We'll fix that in the next release and add an explanation to our documentation.

Alright thank you, excited to see the documentation as right now it’s very confusing, but that’s because it’s a beta ofc.

**Comment by LaAerooo** [comment]
> Metalness doesn't have an apparent effect unless you set up your place to use physically based lighting. To do this, set:
> 
> Lighting.EnvironmentDiffuseScale = 1
> Lighting.EnvironmentSpecularScale = 1 **--(Fixed my typo)**
> Lighting.OutdoorAmbient = 0,0,0
> Lighting.Ambient = 0,0,0
> 
> Currently EnvironmentDiffuseScale and EnvironmentSpecularScale are hidden in the properties window. You can still modify them from Lua. We'll fix that in the next release and add an explanation to our documentation.

Still cannot get any reflections from the skybox, however metalness works.

**Comment by shhshshhs** [comment]
I don't understand, where do you have to put this code? Do I gotta create a Script under lighting and then insert this code? Or what?

**Comment by WatermelonArray** [comment]
@shhshshhs 
You can place the code into the command line.
You can do so like this:
Step 1:
![image](https://user-images.githubusercontent.com/34957838/70855811-f622f500-1ec8-11ea-8781-00a455529153.png)
Step 2:
![image](https://user-images.githubusercontent.com/34957838/70855826-25396680-1ec9-11ea-9539-54b9259501d7.png)
Code:
```Lua
local Lighting = game:GetService("Lighting")
Lighting.EnvironmentDiffuseScale = 1
Lighting.EnvironmentSpecularScale = 1 
Lighting.OutdoorAmbient = Color3.new(0,0,0)
Lighting.Ambient = Color3.new(0,0,0)
```

**Comment by sluncelyna2** [comment]
I agree

**Comment by LaAerooo** [comment]
Ignore the reflections bug, its not a bug i just accidentally set my rendering (engine?) to open gl

**Comment by jbrosnihan-roblox** [comment]
There properties now show up in the Lighting PropertiesWindow. Make sure to get the latest release build.

**Comment by DeletedUserc91a9877** [comment]
@WatermelonArray that did work but how do i get rid of the blue tint

**Comment by jbrosnihan-roblox** [comment]
@DeletedUserc91a9877 the blue tint is the light coming from the sky. I recommend importing a better skybox. There's more documentation explaining these new lighting properties here: https://roblox.github.io/avatar-evolution/surface-appearance

**Comment by DeletedUserc91a9877** [comment]
@jbrosnihan-roblox Thank you
