### ISSUE TITLE
(Question) Motor6Ds auto-initialize?

### ISSUE THREAD

**Issue by Exsolutus** [Roblox/avatar-evolution#43]
I've been working with the NPC character provided in the TestPlace file for the new character controller, and I noticed that the Motor6Ds in the character have no Part0 or Part1 set, but when running the game, somewhere along the line they get set. 

I haven't been able to find any script handling this, so I was wondering if the Motor6Ds are automatically initializing their Part0 and Part1 based on attachments in their parent part?

**Comment by RobloxCodeWriter** [comment]
The RigScale component initializes the Motors as it is setup.

**Comment by Exsolutus** [comment]
Disregard. I found the BuildRigFromAttachments in ServerRigScale.lua
