### ISSUE TITLE
Issue when when scaling a mesh inside studio

### ISSUE THREAD

**Issue by DrProfesor** [Roblox/avatar-evolution#45]
After a mesh has been imported the animations seems to work fine: https://i.imgur.com/HxsLuYV.gifv
But when I try to scale the mesh down some of the bones do not respect that: https://i.imgur.com/WpQ5WjI.gifv

**Comment by adrianlongland** [comment]
Scaling of bones for skinned mesh is not fully supported. The best way is to make the mesh at the desired size, or use the .fbx scale export settings to get the size you need. That said, there is some support for scaling in Studio...
When scaling down, are you using the Studio scale widget?
This will affect the bone translations as the mesh scale changes, and works fine provided the animation does not have any translation data. If it does then the translations will not be scaled to the size of the mesh, and will result in squash or stretch as you are seeing.
I've experimented with reading the mesh scale and applying that to the bone translation data from the animations - however this slows down the calculation considerably.
The long term plan is to handle scaling more generally at the Model level, in the meantime I recommend the suggestions above.
One other possibility is to write a script to scale the translation in the animation key frames.

**Comment by DrProfesor** [comment]
Ahh ok, I'll scale down the fbx for now. I was scaling with the studio widget, and the animations do have translation data. 

Glad to hear it will eventually be supported!
