### ISSUE TITLE
(Question/Suggestion) No property for AO map

### ISSUE THREAD

**Issue by Rocky28447** [Roblox/avatar-evolution#7]
This is less of an issue and more of a question/suggestion. I've noticed that the SurfaceAppearance class has no spot for an Ambient Occlusion map. Are there plans to support this in the future?

**Comment by jbrosnihan-roblox** [comment]
We want to improve occlusion for cavities but we're still talking internally about whether AO maps are the best way. We may be able to develop an automatic solution that works better.
